source 'https://rubygems.org'

gem 'awesome_print'
gem 'better_errors'
gem 'dotenv'
gem "facets", require: false
gem 'kiba-common'
gem 'kiba'

group :development, :test do
  gem 'factory_bot'
  gem 'faker'
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end
