# source 'http://172.31.33.237:9292/'

source 'https://rubygems.org'

gem 'aws-sdk'
gem 'pry'

group :development, :test do
  gem 'factory_girl'
  gem 'faker'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'headless'
  gem 'rspec-ruby'
  gem 'rubocop'
end
